### ISSUE TITLE
Propuesta de mejora

### ISSUE THREAD

**Issue by EleDiaz** [Dariasteam/JSON-cpp#3]
Poder acceder a los valores de JSON de la siguiente forma:

``` c++
tree.getString ("key_5.sub_key_2[1]") // En los vectores

tree.getString ("key_5.sub_key_2['item3']") // En los Hash
```

**Comment by Dariasteam** [comment]
He añadido la opción de utilizar `[indice]` en vectores de forma opcional. En el caso de los hashes no le veo sentido, ya que toda la ruta hasta un elemento final está compuesta o bien de hashes o de vectores, por lo que lo que has escrito debería ser en realidad `tree.getString ("['key_5'].['sub_key_2'].['item3']")` lo que complica innecesariamente la ruta
